all:
	pdflatex -output-directory ./pdf presentazione.tex
	cd ./pdf && rm -fr *.dvi *.aux *.nav *.out *.snm *.toc *.log

handout:
	pdflatex -output-directory ./pdf presentazione_handout.tex
	cd ./pdf && rm -fr *.dvi *.aux *.nav *.out *.snm *.toc *.log
